export const products = [
  {
    ids: 1,
    name: "SCARLET NEXUS",
    slug: "scarlet-nexus-ps4",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/scarlet-nexus-ps4-26276/main-362x461.webp",
    sell_price: 12.99,
    old_price: 15.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS4",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "In a far distant future, a psionic hormone was discovered in the human brain, granting people extra-sensory powers and changing the world as we know it. Just as humanity was entering this new era, deranged mutants known as Others began to descend from the sky with a thirst for human brains. Highly resistant to conventional attack methods, extreme measures needed to be taken to battle the overwhelming threat and preserve humanity. Those with acute extra-sensory abilities, known as psionics, were our chance to fight the onslaught from above. To this day, psionics have been scouted for their talents and recruited to the Other Suppression Force (OSF), humanity's last line of defense.",
  },
  {
    ids: 2,
    name: "God of War Ragnarok",
    slug: "god-of-war-ragnarok-ps4",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/god-of-war-ragnarok-ps4-31118/main-340x461.webp",
    sell_price: 54.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS4",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Embark on a mythic journey for answers and allies before Ragnarök arrives in God of War Ragnarok on PS5. Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. Against a backdrop of Norse Realms torn asunder by the fury of the Aesir, they've been trying their utmost to undo the end times. But despite their best efforts, Fimbulwinter presses onward.",
  },
  {
    ids: 3,
    name: "Fifa 18",
    slug: "fifa-18-ps4",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/fifa-18-ps4-14130/main-366x461.webp",
    sell_price: 7.49,
    old_price: 16.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS4",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Build your dream team in FIFA 18. The in-game points will let you perfect and upgrade your squad. Use them to buy and open packs in in Ultimate Team Mode for FIFA 18. When you do, you'll discover a variety of new players and new items to help you create your “ultimate” roster!",
  },
  {
    ids: 4,
    name: "Assassins Creed The Ezio Collection",
    slug: "assassins-creed-the-ezio-collection-ps4",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/assassin-s-creed-the-ezio-collection-ps4-16037/main-340x461.webp",
    sell_price: 17.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS4",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Live the complete saga of Master Assassin Ezio Auditore da Firenze, the most iconic leader of the Brotherhood of Assassins, as you seek vengeance for the betrayal of your family in a time of greed, corruption, and murderous conspiracy. Including three critically acclaimed single-player campaigns and featuring over 80 hours of gameplay with enhanced graphics, Assassin's Creed® The Ezio Collection brings these enduring adventures to life for the first time on Xbox One and PlayStation®4 system.",
  },
  {
    ids: 5,
    name: "CYBERPUNK 2077",
    slug: "cyberpunk-2077-ps4",
    image:
      "https://media.gamestop.com/i/gamestop/11094722/Cyberpunk-2077---PlayStation-4?$pdp$$&fmt=webp",
    sell_price: 19.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS4",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Cyberpunk 2077 on PS4 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character's cyberware, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.",
  },
  {
    ids: 6,
    name: "Star Wars Jedi: Survivor",
    slug: "star-wars-jedi-survivor-ps5",
    image: "https://media.4rgos.it/s/Argos/3186677_R_SET?$Main768$&w=620&h=620",
    sell_price: 64.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS5",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The story of Cal Kestis continues in Star Wars Jedi: Survivor™, a third person galaxy-spanning action-adventure game from Respawn Entertainment, developed in collaboration with Lucasfilm Games. This narratively-driven, single player title picks up five years after the events of Star Wars Jedi: Fallen Order™ and follows Cal's increasingly desperate fight as the galaxy descends further into darkness. To survive, players will build upon Cal's training with an expanded list of iconic Force abilities, combat stances, and lightsaber customizations that can be combined in new and different ways to fight as a Jedi. While the Force is a powerful ally, it may not be enough. Cal will have to get creative and master new abilities, tactics and even leverage the environment around him to overcome the obstacles ahead.",
  },
  {
    ids: 7,
    name: "Resident Evil Village",
    slug: "resident-evil-village-ps5",
    image:
      "https://media.gamestop.com/i/gamestop/11114710/Resident-Evil-Village---PlayStation-5?$pdp2x$",
    sell_price: 18.99,
    old_price: 25.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS5",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Experience survival horror like never before in Resident Evil Village on PS5. Elevate each desperate fight to survive by showcasing the most realistic and terrifying graphics to date. The all-new title is the eighth major installment in the storied Resident Evil franchise, which established the survival horror genre nearly 25 years ago. The title is currently in development using Capcom’s proprietary RE Engine, used to create vivid gameplay experiences in hit titles such as Resident Evil™ 7 biohazard, Resident Evil™ 2, Resident Evil™ 3, and Devil May Cry™ 5. With hyper-detailed graphics, intense first-person action and masterful storytelling, the terror has never felt more realistic and inescapable.",
  },
  {
    ids: 8,
    name: "Atomic Heart",
    slug: "atomic-heart-ps5",
    image:
      "https://media.gamestop.com/i/gamestop/20002961-680826cd?$pdp$$&fmt=webp",
    sell_price: 69.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS5",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Welcome to a utopian world of wonders and perfection, in which humans live in harmony with their loyal and fervent robots. Well, that's how it used to be. With the launch of the latest robot-control system mere days away, only a tragic accident or a global conspiracy could disrupt it…",
  },
  {
    ids: 9,
    name: "Hogwarts Legacy",
    slug: "hogwarts-legacy-ps5",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/hogwarts-legacy-ps5-28046/main-340x461.webp",
    sell_price: 64.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS5",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. For the first time, experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. Now you can take control of the action and be at the center of your own adventure in the wizarding world. Your legacy is what you make of it. Live the unwritten.",
  },
  {
    ids: 10,
    name: "The Callisto Protocol",
    slug: "the-callisto-protocol-ps5",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/the-callisto-protocol-ps5-33068/main-352x461.webp",
    sell_price: 23.99,
    old_price: 28.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS5",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "In this narrative-driven, third-person survival horror game set 300 years in the future, the player will take on the role of Jacob Lee - a victim of fate thrown into Black Iron Prison, a maximum-security penitentiary located on Jupiter's moon, Callisto. When inmates begin to transform into monstrous creatures, the prison is thrown into chaos. To survive, Jacob must battle his way to safety to escape Black Iron Prison, while uncovering the dark and disturbing secrets buried beneath the surface of Callisto. Using a unique blend of shooting and close-quarters combat, Jacob will need to adapt his tactics to combat the rapidly evolving creatures while scavenging to unlock new weapons, gear, and abilities to outrun the growing threat and escape the horrors of Jupiter's Dead Moon.",
  },
  {
    ids: 11,
    name: "Dark Souls",
    slug: "dark-souls-ps3",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/dark-souls-essentials-ps3-28525/main-340x461.webp",
    sell_price: 18.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS3",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Dark Souls is the spiritual successor to From Software's widely acclaimed action RPG Demon's Souls. Dark Souls is a new action role-playing game set in a rich and dark fantasy universe. The game breaks down barriers with a flawless world design that encourages exploration and fosters an adaptable gameplay experience.",
  },
  {
    ids: 12,
    name: "Grand Theft Auto V",
    slug: "grand-theft-auto-v-ps3",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/grand-theft-auto-v-ps3-10559/main-373x461.webp",
    sell_price: 26.49,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS3",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Welcome to Los Santos where self-help gurus, starlets, and fading celebrities, once the envy of the Western world, are now struggling to stay afloat. In Grand Theft Auto V, you follow the epic storylines of A young street hustler, a retired bank robber and a terrifying psychopath. The trio must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.",
  },
  {
    ids: 13,
    name: "Hitman Absolution",
    slug: "hitman-absolution-ps3",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/hitman-absolution-playstation-3-ps3-34152/main-352x461.webp",
    sell_price: 13.99,
    old_price: 18.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS3",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "In Hitman: Absolution, the assassin will have his most personal contract yet. See the world through the eyes of Agent 47 and become the most dangerous assassin. Betrayed by the Agency and hunted by the police, Agent 47 seeks escape in a corrupt world. Technology Glacier 2 - Hitman: Absolution was built from the ground up and features a cinematic story and high-quality audio and video design.",
  },
  {
    ids: 14,
    name: "Resident Evil Operation Raccoon City",
    slug: "resident-evil-operation-raccoon-city-ps3",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/resident-evil-operation-raccoon-city-ps3-12093/main-343x461.webp",
    sell_price: 37.69,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS3",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,

    description:
      "Resident Evil: Operation Raccoon City offers a true third-person shooter experience set in the dark and sinister Resident Evil universe.The setting of the Resident Evil universe not only provides a rich backdrop to the action, but also offers unique and thrilling triple-threat combat. Zombies and Bio-Organic Weapons (BOWs) add to the mix as players not only compete against their team's opposing team, but also tackle this unpredictable third element that could only exist in the twisted Resident Evil universe, creating a style of new game.",
  },
  {
    ids: 15,
    name: "The Walking Dead Survival Instinct",
    slug: "the-walking-dead-survival-instinct-ps3",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/the-walking-dead-survival-instinct-ps3-17653/main-313x461.webp",
    sell_price: 39.89,
    rent_price: 2.5,
    category: "Games",
    brand: "Playstation",
    brandType: "PS3",
    val: "games/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The Walking Dead video game takes the place of the undead and brings them out of the AMC Emmy Award-winning TV show and into console gaming systems in a new, terrifying way. The action game Terminal Reality will allow players to assume the role of mysterious survivor Daryl Dixon on an unforgiving journey to the supposed safety of Atlanta. The iconic walkers will relentlessly hunt players like TV partners using a combination of sight, sound and smell. As Daryl, players will have to carefully navigate each new area they explore. Once discovered, it doesn't take much to attract an unstoppable horde of pilgrims, so every threat must be assessed and every situation analyzed. No place is truly safe for Daryl as he makes his way through rural Georgia with his creepy brother Merle in this new, post-apocalyptic world.",
  },
  {
    ids: 16,
    name: "Call of Duty Modern Warfare Remastered",
    slug: "call-of-duty-modern-wafare-remastered-xboxone",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/call-of-duty-modern-warfare-remastered-xbox-one-13378/main-343x461.webp",
    sell_price: 24.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox One",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "One of the most critically-acclaimed games in history, Call of Duty®: Modern Warfare is back, remastered in true high-definition. Call of Duty® 4: Modern Warfare® set a new standard upon its original release for intense, cinematic action, while receiving universal praise as one of the most influential video games of all-time. Relive one of the most iconic campaigns in history, as you are transported around the globe. You'll suit up as unforgettable characters Sgt. John Soap MacTavish, Capt. John Price and more, as you battle a rogue enemy group across global hotspots from Eastern Europe and rural Russia, all the way to the Middle East.",
  },
  {
    ids: 17,
    name: "Zoo Tycoon",
    slug: "zoo-tycoon-xboxone",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/zoo-tycoon-xbox-one-13602/main-352x461.webp",
    sell_price: 9.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox One",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Let your imagination run wild with Zoo Tycoon on Xbox One! Choose from over 100 visually stunning animals and the largest, most detailed selection of environments ever, then build, manage and maintain your dream zoo alone or with up to four players on Xbox LIVE. For added fun, upload your creation to the cloud and work together with other Tycoons to care for and share your animals. With intuitive, easy-to-use controls and Kinect-enabled features that allow your animals to recognize your voice and react to your movements, this zoo simulation will charm animal lovers of all ages.",
  },
  {
    ids: 18,
    name: "Prey",
    slug: "prey-xboxone",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/prey-xbox-one-10779/main-340x461.webp",
    sell_price: 6.99,
    old_price: 12.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox One",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "In Prey, you awaken aboard Talos I, a space station orbiting the moon in the year 2032. You are the key subject of an experiment meant to alter humanity forever - but things have gone terribly wrong. The space station has been overrun by hostile aliens and you are now being hunted. As you dig into the dark secrets of Talos I and your own past, you must survive using the tools found on the station, your wits, weapons, and mind-bending abilities.",
  },
  {
    ids: 19,
    name: "Titanfall",
    slug: "titanfall-xboxone",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/titanfall-xbox-one-10408/main-340x461.webp",
    sell_price: 17.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox One",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Wait for Titanfall. Created by the master developers behind the CALL OF DUTY franchise, Titanfall is the first next-gen shooter that combines pure adrenaline, wall-running and double-jumping action with powerful and fast-paced titan warfare to set a new standard for online multiplayer gaming. Offering fast and fluid combat that gives you the freedom to fight as elite, assault pilots, or nimble and heavily armored titans.",
  },
  {
    ids: 20,
    name: "ASSASSINS CREED ROGUE REMASTERED",
    slug: "assassins-creed-rogue-remastered-xboxone",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/assassins-creed-rogue-remastered-xbox-one-15559/main-313x461.webp",
    sell_price: 29.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox One",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Experience the darkest chapter in Assassin's Creed lore yet, remastered for next-gen platforms. Assume the role of Shay, an Assassin during the French and Indian War, and witness the cataclysmic events that force him to betray the Brotherhood in order to prevent further catastrophe.",
  },
  {
    ids: 21,
    name: "Call of Duty Black Ops Cold War",
    slug: "call-of-duty-black-ops-cold-war-xboxseriesx",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/call-of-duty-black-ops-cold-war-xbox-series-x-22502/main-338x461.webp",
    sell_price: 19.99,
    old_price: 22.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox Series X",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The iconic Black Ops series is back with Call of Duty®: Black Ops Cold War on Xbox One - the direct sequel to the original and fan-favorite Call of Duty®: Black Ops. CoD Black Ops Cold War will drop fans into the depths of the Cold War’s volatile geopolitical battle of the early 1980s. Nothing is ever as it seems in a gripping single-player Campaign, where players will come face-to-face with historical figures and hard truths, as they battle around the globe through iconic locales like East Berlin, Vietnam, Turkey, Soviet KGB headquarters and more.",
  },
  {
    ids: 22,
    name: "FIFA 22",
    slug: "fifa-22-xboxseriesx",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/fifa-22-xbox-series-27210/main-340x461.webp",
    sell_price: 18.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox Series X",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "GameHunt joins the game with FIFA 22 on Xbox Series X! Elevate your game to a new level, score points, attack plays, and break down the defense in this highly-anticipated sports video game. Powered by Football™, EA SPORTS™ FIFA 22 on PlayStation 5 and Xbox Series X|S moves the game forward with groundbreaking next-gen HyperMotion gameplay technology that elevates every moment on the pitch.",
  },
  {
    ids: 23,
    name: "Gotham Knights",
    slug: "gotham-knights-xboxseriesx",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/gotham-knights-xbox-series-28583/main-340x461.webp",
    sell_price: 29.99,
    old_price: 37.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox Series X",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "With the death of the Caped Crusader, who will step up to defend the streets of Gotham City? Team up with DC Hero’s Batgirl, Nightwing, Red Hood, and Robin in Gotham Knights. Protect the citizens from a crime-ridden open world with action-packed gameplay and uncover Gotham's darkest history in this epic, Batman video game.",
  },
  {
    ids: 24,
    name: "A Plague Tale Requiem",
    slug: "a-plague-tale-requiem-xboxseriesx",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/a-plague-tale-requiem-xbox-series-30588/main-340x461.webp",
    sell_price: 37.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox Series X",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "After escaping their devastated homeland, Amicia and Hugo travel far south, to new regions and vibrant cities. But, when Hugo’s powers reawaken, death and destruction return in a flood of devouring rats. Forced to flee once more, the siblings place their hopes in a prophesized island that may hold the key to saving Hugo.",
  },
  {
    ids: 25,
    name: "The Quarry",
    slug: "the-quarry-xboxseriesx",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/the-quarry-xbox-series-29939/main-340x461.webp",
    sell_price: 18.99,
    old_price: 22.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox Series X",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "From the developers of Until Dawn and Dark Pictures comes an all-new horror video game experience, The Quarry on Xbox One. When the sun goes down on the last night of summer camp, nine teenage counselors are plunged into an unpredictable night of horror. The only thing worse than the blood-drenched locals and creatures hunting them are the unimaginable choices you must make to help them survive.",
  },
  {
    ids: 26,
    name: "Lego The Hobbit",
    slug: "lego-the-hobbit-xbox360",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/lego-the-hobbit-xbox-360-13652/main-325x461.webp",
    sell_price: 30.29,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox 360",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "From the creators of the hugely popular LEGO® The Lord of the Rings comes LEGO The Hobbit, inspired by the first two films in The Hobbit Trilogy: The Hobbit: An Unexpected Journey and the upcoming film The Hobbit: The Desolation of Smaug, produced by New Line Cinema and Metro-Goldwyn -Mayer Pictures (MGM) as well as the LEGO The Hobbit building set collection.",
  },
  {
    ids: 27,
    name: "Army of Two The Devils Cartel",
    slug: "army-of-two-the-devils-cartel-xbox360",
    image:
      "https://www.jocurinoi.ro/image/cachewebp//data/imported/army-of-two-the-devil-s-cartel-xbox-360-13562/main-343x461.webp",
    sell_price: 23.79,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox 360",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The originator of tactical co-op is back! Developed by Visceral games, the award-winning creators of Dead Space, Army of Two The Devil's Cartel delivers a co-op action shooter that's built on the new Frostbite 2 engine for maximum destruction. You and your partner must shoot and destroy everything in your path to take down a violent drug cartel that has taken over Mexico. In completing partner-based missions, each player must tackle and overcome individual objectives in order to achieve a common goal. The more effective your teamwork, the greater the reward, as the new Overkill mode gives you devastating power for truly epic mass destruction! Experience this explosive action-blockbuster campaign in two local coalitions with split-screen or online co-op!",
  },
  {
    ids: 28,
    name: "South Park The Stick Of Truth",
    slug: "south-park-the-stick-of-truth-xbox360",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/south-park-the-stick-of-truth-xbox-360-15427/main-340x461.webp",
    sell_price: 20.29,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox 360",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "From the dangerous battlefields of the fourth grade playground, a young hero will rise, brand to be the savior of South Park. From South Park creators Trey Parker and Matt Stone comes an epic attempt to become...cool. For a thousand years the battle was fought. The only reason humans and elves are locked in a war that never ends: the Staff of Truth.",
  },
  {
    ids: 29,
    name: "Dragon Age Inquisition",
    slug: "dragon-age-inquisition-xbox360",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/dragon-age-inquisition-xbox-360-13341/main-340x461.webp",
    sell_price: 12.09,
    old_price: 14.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox 360",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Dragon Age Inquisition is a role playing game released by Electronic Arts, we expect Bioware to announce a new main character who will join the group composed of Warden and Hawke. BioWare wants to combine elements from the previous games in the new Dragon Age Inquisition game, among other things, the battles will focus more on the ability of the players to prepare to position themselves and form a well-knit team with the characters in the game which will it requires fewer movements but more thinking.",
  },
  {
    ids: 30,
    name: "Prince Of Persia",
    slug: "prince-of-persia-xbox360",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/prince-of-persia-xbox-360-12879/main-325x461.webp",
    sell_price: 17.09,
    rent_price: 2.5,
    category: "Games",
    brand: "Xbox",
    brandType: "Xbox 360",
    val: "games/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Prince of Persia is set in a land rooted in ancient Persian mythology, the prince finds himself in an epic battle between the primal forces of light and darkness - the god of Light, Ormazd versus his brother Ahriman, the destroyer of darkness. The prince arrives just in time to witness the destruction of the legendary Tree of Life, an act that threatens to plunge the entire world into eternal darkness. Manifested in the form of corruption, a dark substance that physically contaminates the earth and sky, the prince must team up with his new deadly companion, Elika, to cure the world of the evil corruption.",
  },
  {
    ids: 31,
    name: "Rock Band",
    slug: "rock-band-nintendowii",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/rock-band-wii-12519/main-335x461.webp",
    sell_price: 7.39,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Wii",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The game allows up to four players to simulate the performance of popular rock songs by playing with controllers modeled after musical instruments. Players can play the lead guitar, bass guitar, and drums parts to songs with instrument controllers, as well as sing through a USB microphone. Players are scored on their ability to match scrolling musical notes while playing instruments, or by their ability to match the singer's pitch on vocals. ",
  },
  {
    ids: 32,
    name: "THE SIMS 3",
    slug: "the-sims-3-nintendowii",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/the-sims-3-wii-13982/main-343x461.webp",
    sell_price: 18.19,
    old_price: 22.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Wii",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The Sims 3 Wii Games The Sims 3 finally comes to consoles and has exclusive features for each. Create any Sim you want and give it a unique personality. you can make him romantic, evil, paranoid, kleptomaniac or a combination of many other elements. During the game you will get points and unlock karma powers. You can give instant joy, beauty or love - or you can remove them immediately. Special for the Nintendo Wii version: in the new Life Moments Game mode you can play with three more friends and you will bet on important moments to win points and rewards. You have at your disposal a new location - the beach, with a new climate, new residents, careers, Karma powers and for the first time you will be able to directly control your senses.",
  },
  {
    ids: 33,
    name: "Monsters vs. Aliens",
    slug: "monsters-vs-aliens-nintendowii",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/monsters-vs.-aliens-wii-12506/main-335x461.webp",
    sell_price: 11.39,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Wii",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Based on the animated film, Activision's Monsters vs Aliens for Nintendo Wii captures the fun and action of the film. Players can choose to play as any of the following characters: the missing link, half monkey and half fish; B.O.B., gelatinous and indestructible mass; Ginormica, the gigantic woman; and Insectosaurus, the giant insect.",
  },
  {
    ids: 34,
    name: "Sonic Colours",
    slug: "sonic-colours-nintendowii",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/sonic-colours-wii-12526/main-327x461.webp",
    sell_price: 21.09,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Wii",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The diabolical Dr. Eggman has hatched another plan for world domination! He has built an amazing interstellar amusement park, floating in space around Sonic's home planet, bursting with incredible rides and attractions. However, it's still not as it seems Dr. Eggman has kidnapped an alien race called Wisps and is harnessing their colorful energy to fuel a sinister plot. However, before Dr. Eggman can complete his evil plans, Sonic discovers the mysterious theme park in space. When he arrives, Sonic finds that he is able to use these alien powers and is ready to help! Sonic will need all his speed and skill as he faces this test, but empowered by alien energy, it's a test he'll pass with flying colors!",
  },
  {
    ids: 35,
    name: "Driver Parallel Lines",
    slug: "driver-parallel-lines-nintendowii",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/driver-parallel-lines-wii-12486/main-328x461.webp",
    sell_price: 20.49,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Wii",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Driver: Parallel lines define the action as a genre. It is one of the first action games to incorporate online play and has taken car chases back to Hollywood style. Discover Tk, a driver for hire and free from conscience. Take part in a series of adrenaline pumping tales of revenge set in the New York underworld. Massive improvements to everything from character control to Ai to weapon selection effects",
  },
  {
    ids: 36,
    name: "Crysis Remastered",
    slug: "crysis-remastered-nintendoswitch",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/crysis-remastered-nintendo-switch-27656/main-280x461.webp",
    sell_price: 34.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Switch",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The classic first person shooter from Crytek is back with the action-packed gameplay, sandbox world, and thrilling epic battles you loved the first time around. What begins as a simple rescue mission becomes the battleground of a new war as alien invaders swarm over a North Korean island chain. Armed with a powerful Nanosuit, players can become invisible to stalk enemy patrols, or boost strength to lay waste to vehicles. The Nanosuit's speed, strength, armor, and cloaking allow creative solutions for every kind of fight, while a huge arsenal of modular weaponry provides unprecedented control over play style. In the ever-changing environment, adapt tactics and gear to dominate your enemies, in an enormous sandbox world.",
  },
  {
    ids: 37,
    name: "The Legend of Zelda: Breath of the Wild",
    slug: "the-legend-of-zelda-breath-of-the-wild",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/the-legend-of-zelda-breath-of-the-wild-nsw-12338/main-284x461.webp",
    sell_price: 50.99,
    old_price: 54.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Switch",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Forget everything you know about The Legend of Zelda games. Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule in this stunning Open-Air Adventure. Now on Nintendo Switch, your journey is freer and more open than ever. Take your system anywhere, and adventure as Link any way you like.",
  },
  {
    ids: 38,
    name: "POKEMON LETS GO PIKACHU",
    slug: "pokemon-lets-go-pikachu-nintendoswitch",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/pokemon-lets-go-pikachu-nsw-17382/main-284x461.webp",
    sell_price: 49.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Switch",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The next step in your Pokémon™ journey starts here Take a Pokémon™ journey to the Kanto region with your energetic partner, Pikachu! Become the best Pokémon Trainer as you battle other Trainers, Gym Leaders, and the sinister Team Rocket. Catch Pokémon in the wild using a gentle throwing motion with either a Joy-Con™ controller or a Poké Ball™ Plus accessory, which will light up, vibrate, and make sounds to bring your adventure to life. You can also use button controls in Handheld Mode. Share your adventure with family or friends using a second Joy-Con or Poké Ball Plus (sold separately). You can even connect to the Pokémon™ GO app* using a compatible smartphone to bring over Pokémon originally discovered in the Kanto region!",
  },
  {
    ids: 39,
    name: "Animal Crossing: New Horizons",
    slug: "animal-crossing-new-horizons-nintendoswitch",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/animal-crossing-new-horizons-nsw-25193/main-284x461.webp",
    sell_price: 50.99,
    old_price: 54.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Switch",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Escape to a deserted island and create your own paradise as you explore, create, and customize in the Animal Crossing: New Horizons game. Your island getaway has a wealth of natural resources that can be used to craft everything from tools to creature comforts. You can hunt down insects at the crack of dawn, decorate your paradise throughout the day, or enjoy sunset on the beach while fishing in the ocean. The time of day and season match real life, so each day on your island is a chance to check in and find new surprises all year round. Get ready to make a splash in your own island paradise. A series of free updates* to the Animal Crossing: New Horizons game for the Nintendo Switch system will deliver new features, including the ability to swim and dive for sea creatures. You'll also get to interact with fresh faces and discover a variety of new items, including mermaid-themed furniture. These free updates are among some of the new experiences coming to your island life over the course of the summer and beyond.",
  },
  {
    ids: 40,
    name: "Super Mario Odyssey",
    slug: "super-mario-odyssey-nintendoswitch",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/super-mario-odyssey-nsw-14811/main-284x461.webp",
    sell_price: 54.99,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo Switch",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Embark on a cap-tivating, globe-trotting adventure! Join Mario on a massive, globe-trotting 3D adventure and use his incredible new abilities to collect Moons so you can power up your airship, the Odyssey, and rescue Princess Peach from Bowser's wedding plans! This sandbox-style 3D Mario adventure—the first since 1996's beloved Super Mario 64 and 2002's Nintendo GameCube classic Super Mario Sunshine—is packed with secrets and surprises, and with Mario's new moves like cap throw, cap jump, and capture, you'll have fun and exciting gameplay experiences unlike anything you've enjoyed in a Mario game before. Get ready to be whisked away to strange and amazing places far from the Mushroom Kingdom!",
  },
  {
    ids: 41,
    name: "Lego Star Wars The Force Awakens",
    slug: "lego-star-wars-the-force-awakens-nintendo3ds",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/lego-star-wars-the-force-awakens-n3ds-10844/main-340x461.webp",
    sell_price: 19.29,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo 3DS",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The game includes exclusive content that will take players on an adventure between Star Wars: Return of the Jedi and Star Wars: The Force Awakens, providing more information about the new film and its characters. The number one LEGO video game franchise returns with a fun and humorous journey in the new Star Wars adventure!",
  },
  {
    ids: 42,
    name: "Monster 4 X 4",
    slug: "monster-4x4-nintendo3ds",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/monster-4-x-4-nintendo-3ds-21259/main-352x461.webp",
    sell_price: 22.29,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo 3DS",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The originator of tactical co-op is back! Developed by Visceral games, the award-winning creators of Dead Space, Army of Two The Devil's Cartel delivers a co-op action shooter that's built on the new Frostbite 2 engine for maximum destruction. You and your partner must shoot and destroy everything in your path to take down a violent drug cartel that has taken over Mexico. In completing partner-based missions, each player must tackle and overcome individual objectives in order to achieve a common goal. The more effective your teamwork, the greater the reward, as the new Overkill mode gives you devastating power for truly epic mass destruction! Experience this explosive action-blockbuster campaign in two local coalitions with split-screen or online co-op!",
  },
  {
    ids: 43,
    name: "Rayman Origins",
    slug: "rayman-origins-nintendo3ds",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/rayman-origins-nintendo-nintendo-3ds-29930/main-340x461.webp",
    sell_price: 35.59,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo 3DS",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Michel Ancel, the acclaimed creator of Rayman, Beyond Good & Evil and Raving Rabbids, returns to his roots to bring us Rayman Origins: a high-definition, four-player, fully co-op 2D side-scrolling platform adventure. Play Rayman Origins and discover or rediscover the magical universe and legendary 2D gameplay that won the hearts of millions of fans. When the Glade of Dreams is invaded by angry Darktoons, the Fairy Council hastily summons Rayman to save the day, but the hero of light isn't quite all.Together, the world's funniest team of heroes will have to restore peace to the Glade, or watch their beloved home disappear like a bad dream.",
  },
  {
    ids: 44,
    name: "Rise Of The Guardians",
    slug: "rise-of-the-guardians-nintendo3ds",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/rise-of-the-guardians-nintendo-3ds-30616/main-340x461.webp",
    sell_price: 20.19,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo 3DS",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Let your imagination run wild in Rise of the Guardians: The Video Game as you play as one of the classic childhood legends including: North (aka Santa Claus), Tooth (aka Fairy Tail), Bunnymund (aka Bunnymund Easter), Sandman and Jack Frost. In this action-packed adventure game, each Guardian has their own set of upgradable and extraordinary abilities that will help you face the evil spirit Pitch and his contagious nightmares.",
  },
  {
    ids: 45,
    name: "Batman Arkham Origins Blackgate",
    slug: "batman-arkham-origins-blackgate",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/batman-arkham-origins-blackgate-n3ds-13360/main-343x461.webp",
    sell_price: 17.79,
    rent_price: 2.5,
    category: "Games",
    brand: "Nintendo",
    brandType: "Nintendo 3DS",
    val: "games/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Batman: Arkham Origins Blackgate is a 2.5D game developed by Armature Studio that brings the Batman Arkham experience to Nintendo and Sony handheld systems for the first time. A companion game to Batman: Arkham Origins, players can continue the story of the console version and discover more details about the Dark Knight's past.",
  },
  {
    ids: 46,
    name: "Elden Ring",
    slug: "elden-ring-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/elden-ring-pc-27930/main-327x461.webp",
    sell_price: 7.39,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Elden Ring is an action-RPG adventure game developed by FromSoftware Inc. and produced by BANDAI NAMCO Entertainment Inc. The action is set in a vast land in a rich and bloody history, created by Hidetaka Miyazaki - the creator of the DARK SOULS series of video games. In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, was shattered. Marika's descendants, all demigods, claimed the remnants of the Elden Ring known as the Great Runes, sparking a war: The Shattering. A war that meant the abandonment of Greater Will.",
  },
  {
    ids: 47,
    name: "The Evil Within",
    slug: "the-evil-within-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/the-evil-within-pc-25277/main-327x461.webp",
    sell_price: 2.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Developed by Shinji Mikami and the talented team at Tango Gameworks, The Evil Within embodies the essence of pure survival horror. Highly crafted environments, terrifying anxiety, and a complex story combine to create an immersive world that will have you reeling. With limited resources at your disposal, you will fight for survival and experience deep fear in this perfect blend of horror and action.",
  },
  {
    ids: 48,
    name: "Battlefield Hardline",
    slug: "Battlefield-hardline-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/battlefield-hardline-pc-19047/main-340x461.webp",
    sell_price: 29.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Get a piece of the action in Battlefield™ Hardline, a fresh, new take on Battlefield that allows you to live out your cops and criminal fantasy. Combining an emotionally-driven single player story inspired by popular TV crime dramas, and an all-out-war multiplayer on the streets of Los Angeles and Miami, Hardline delivers the most complete FPS on the brandTypeet.",
  },
  {
    ids: 49,
    name: "Agony",
    slug: "agony-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/agony-pc-19258/main-326x461.webp",
    sell_price: 9.99,
    old_price: 22.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Agony is a first-person, survival horror game set in hell. You will begin your journey as a tormented soul within the depths of the underworld, without any memories of your past. Equipped with the special ability to control people on your journey - even possessing demons themselves - you'll have all the necessary tools to survive in the extreme conditions of hell.",
  },
  {
    ids: 50,
    name: "Marvels Guardians of the Galaxy",
    slug: "marvels-guardians-of-the-galaxy-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/marvel-s-guardians-of-the-galaxy-pc-27099/main-328x461.webp",
    sell_price: 17.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Set out on an adventure of a lifetime with Marvel's mightiest band of misfits on Xbox. In Marvel's Guardians of the Galaxy, it's your turn to lead as a star-lord and save the universe. In this third-person action-adventure game, Some jerk (surely not you) has set off a chain of catastrophic events, and only you can hold the unpredictable Guardians together long enough to fight off total interplanetary meltdown.",
  },
  {
    ids: 51,
    name: "Life Is Strange True Colors",
    slug: "life-is-strange-true-colors-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/life-is-strange-true-colors-pc-27289/main-338x461.webp",
    sell_price: 34.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "A bold new era of the award-winning Life is Strange begins, with a new playable main character and a thrilling mystery to solve! Alex Chen has long repressed his curse: the supernatural ability to experience, absorb and manipulate the strong emotions of others, which he sees as bright, colorful auras. When her brother dies in a so-called accident, Alex must embrace her volatile power to learn the truth—and uncover the dark secrets buried by a small town.",
  },
  {
    ids: 52,
    name: "Metro Redux",
    slug: "metro-redux-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/metro-redux-pc-21361/main-326x461.webp",
    sell_price: 9.99,
    old_price: 14.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "In 2013, the world was devastated by an apocalyptic event, annihilating almost all of humanity and turning the surface of the earth into a poisonous wasteland. A handful of survivors took refuge in the depths of Moscow's underground, and human civilization entered a new dark age. The year is 2033. An entire generation has been born and raised underground, and their subway station-cities are fighting for survival; between them and the mutant horrors waiting outside. You are Artyom, born in the last days before the fire, but raised underground. Having never ventured beyond the city limits, a fateful event sparks a desperate mission into the heart of the subway system to warn the remnants of humanity of a terrible impending threat. Your journey takes you from the forgotten catacombs beneath the subway to the desolate wastelands above, where your actions will determine the fate of mankind. But what if the real threat comes from within?",
  },
  {
    ids: 53,
    name: "FarCry6",
    slug: "far-cry-6-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/far-cry-6-pc-29987/main-340x461.webp",
    sell_price: 59.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Far Cry 6 let's you take on the responsibilities of local Yaran and guerilla fighter Dani Rojas. Experience the brilliant open-world gameplay and explore stunning new terrain in this gripping, first-person shooter. Join the revolution and push back against the oppressive regime of dictator Antón Castillo and his teenage son Diego, brought to life by Hollywood stars Giancarlo Esposito and Anthony Gonzalez.",
  },
  {
    ids: 54,
    name: "Angry Birds",
    slug: "angry-birds-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/angry-birds-pc-25221/main-344x461.webp",
    sell_price: 4.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Angry Birds survival is at stake. Enjoy revenge on the green pigs who stole the birds' eggs. Use the unique powers of the Angry Birds to dispel the confusing constructions of the pigs. Angry Birds offers challenging physics-based demolition gameplay with hours and hours of replay value. Each of the 240+ levels requires logic, skill and brute force to crush the enemy.",
  },
  {
    ids: 55,
    name: "FAR CRY PRIMAL",
    slug: "far-cry-primal-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/far-cry-primal-pc-13839/main-329x461.webp",
    sell_price: 6.99,
    old_price: 12.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Welcome to the Stone Age, a time of omnipresent danger and limitless adventure, where giant mammoths and sabretooth tigers rule the Earth and humanity is at the bottom of the food chain. As the last survivor of your tribe, you will learn to craft a deadly arsenal, fend off fierce predators and outsmart enemies to conquer Oros and save Mankind.",
  },
  {
    ids: 56,
    name: "History Great Battles Medieval",
    slug: "history-great-battles-medieval",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/history-great-battles-medieval-pc-13564/main-325x461.webp",
    sell_price: 5.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Great Battles Medieval is a Real Time Strategy game set during the Hundred Years' War. It features different conflicts between England and France and allows you to play as either the English or the French. The English campaign is designed for beginners and you have the opportunity to fight as the Black Prince or Henry V. The French campaign is for experienced players and allows you to command Joan of Arc or the King of France.",
  },
  {
    ids: 57,
    name: "Hunting Simulator",
    slug: "hunting-simulator-pc",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/hunting-simulator-pc-13089/main-355x461.webp",
    sell_price: 7.99,
    rent_price: 2.5,
    category: "Games",
    brand: "PC",
    val: "games/pc",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "A true hunting simulation, Hunting Simulator offers players hours and hours of immersion in the open wilderness with unique and multiplayer modes, a multitude of hunting areas and hundreds of objectives to complete. Developed using the Unreal 4 engine, the game features some of the most famous hunting regions, such as the mountains of Colorado, the oak forests of France and the snowy plains of Alaska. Each hunting area is populated by many different and realistic animals, each with an authentic set of behaviors.",
  },
  {
    ids: 58,
    name: "Playstation 4 Slim Console 500gb",
    slug: "playstation-4-slim-console-500gb",
    image:
      "https://s13emagst.akamaized.net/products/4152/4151785/images/res_ce6d6d5f5e22850225f6916f9380e261.jpg",
    sell_price: 219.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Enjoy incredible, lifelike colors through HDR graphics, 30% smoother and 16% lighter than the original PS4 console. Store games, applications, screenshots and videos on the 500 GB or 1 TB version, all your favorite applications, series, movies and games on one platform.",
  },
  {
    ids: 59,
    name: "Playstation 4 PRO Console 1TB",
    slug: "playstation-4-pro-console-1tb",
    image:
      "https://s13emagst.akamaized.net/products/4152/4151786/images/res_6165020e67d4a370499cb9c87a82f3a8.jpg",
    sell_price: 249.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "PlayStation®4 Pro (PS4®Pro) (CUH-7000 series) is a console designed to offer unique experiences by improving processing power and supporting 4K resolution images. By increasing the performance delivered by the system architecture, both at the CPU level and at the GPU level, PS4 Pro allows for a more detailed rendering of games, with a higher level of details. Users who have 4K televisions will be able to enjoy all PS4 games in better quality, in addition to 4K resolution, benefiting from higher or more stable framerates.",
  },
  {
    ids: 60,
    name: "Console Playstation 5 Digital Edition 825GB SSD",
    slug: "playstation-5-console-825gb",
    image:
      "https://lcdn.mediagalaxy.ro/resize/media/catalog/product/c/o/2bd48d28d1c32adea0e55139a4e6434a/consola_playstation_5_ps5_c_chassis_extra_controller_dualsense_3d_coperta_6fa70e05.png",
    sell_price: 329.99,
    old_price: 359.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The PS5 console offers unexpected new gaming opportunities. Enjoy fast charging, an ultra-fast SSD and exciting features like haptic feedback, adaptive triggers, 3D sound and a new generation of games. The PS5 Digital Edition is a fully digital version of the PS5 console that does not have a disc drive. A custom processor, GPU and integrated SSD, set a completely new standard for PlayStation, great graphics and experience new PS5 features. The innovative Dualsense controller offers precise gameplay and new features.",
  },
  {
    ids: 61,
    name: "Console Playstation 5 Standard Edition 825 Gb Disc + Game Ps5 God Of War Ragnarok",
    slug: "console-playstation-5-standard-god-of-war",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cp/data/imported/consola-playstation-5-standard-edition-825-gb-disc--2B-joc-ps5-god-of-war-ragnarok-ps5-35551/main-340x461.webp",
    sell_price: 459.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "PlayStation 5 - The PS5™ console unleashes new gaming possibilities that you never anticipated. Experience lightning-fast loading with an ultra-fast SSD, deeper immersion with haptic feedback compatibility, adaptive triggers and 3D sound, and a new generation of incredible PlayStation® games.",
  },
  {
    ids: 62,
    name: "Playstation 3 Super Slim Console 500GB Destiny Bundle",
    slug: "playstation-3-super-slim-console",
    image:
      "https://consolevariations.com/storage/images/variations/consoles/playstation-3-super-slim-destiny/large/playstation-3-super-slim-destiny-1553853477-2.jpg",
    sell_price: 49.99,
    old_price: 59.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The redesigned new PlayStation 3 is smaller and lighter than ever; packed with all the gaming fun you'd expect from PlayStation, but in a new shell. By redesigning the internal design architecture and removing the disc feed tray and replacing it with a top-loading sliding cover, the PS3 Super Slim is up to 25% smaller than the current PS3 Slim.",
  },
  {
    ids: 63,
    name: "Console SONY PS3 Super Slim 12 GB",
    slug: "console-sony-ps3-super-slim",
    image:
      "https://images.okr.ro/serve/product/a6cf8f90e92de9effb259591f21a3f2d-27940-1000_1000",
    sell_price: 29.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Playstation",
    val: "consoles/playstation",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The PS3™ system is the first to use the powerful Cell Broadband Engine™ microprocessor. Thus, the console can work at incredible speed and play games with ultra-realistic graphic details. Moreover, the PS3™ system has a FullHD Blu-ray™ player and a capacious hard disk - for your games. Which means that in the evening, you can use the console to watch a FullHD Movie at the highest quality - with Surround sound, and during the day, to play the latest titles. Of course, the disc drive is also compatible with DVD media, which means that you can watch even the oldest movies in the collection, in the best quality.",
  },
  {
    ids: 64,
    name: "Microsoft 500GB Xbox One console",
    slug: "xbox-one-console-500gb",
    image:
      "https://s13emagst.akamaized.net/products/769/768863/images/res_c6ded8f3deb1882157696f2566eddd9e.jpg",
    sell_price: 124.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Welcome to the world of Xbox One! Here you will find the newest generation of games and entertainment! The games will push the limits of reality and the television will listen to your every command. Here you can navigate in a single moment between TV and movies, music or games. Each experience is unique, adapted to your wishes. All in one place, Xbox One.",
  },
  {
    ids: 65,
    name: "Microsoft Xbox One Slim 1TB with Forza Horizon 3 + Hot Wheels DLC",
    slug: "xbox-one-slim-1tb-forza-wheels",
    image:
      "https://p1.akcdn.net/full/463517383.microsoft-xbox-one-s-slim-500gb-forza-horizon-3-hot-wheels.jpg",
    sell_price: 69.99,
    old_price: 89.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The Hot One Wheels Xbox One S Forza Horizon 3 Bundle, featuring a full download of the racing favorite Forza Horizon 3, including the best-selling Hot Wheels expansion and an Xbox Wireless Controller. Drive, explore, jump and race across Australia with over 350 of the world's biggest cars, make your Hot Wheels fantasies come to life with loops, corkscrews, big turns, half pipes, crazy jumps and even mechanical dinosaurs.",
  },
  {
    ids: 66,
    name: "Xbox Series S Console 512GB",
    slug: "xbox-series-s-console-512gb",
    image:
      "https://www.gamers.ro/content/product_instances2/988382/xboxseries-xbox-series-s-512-gb.jpg",
    sell_price: 270.89,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The next generation of games brings the largest digital library to date to the smallest Xbox console. With more dynamic worlds, faster loading times and Xbox Game Pass in the latest all-digital Xbox Series S. Games built with the Xbox Series X Development Kit | S features significantly reduced loading times and stunning visuals at up to 120FPS.",
  },
  {
    ids: 67,
    name: "Xbox Series X Diablo IV Bundle",
    slug: "xbox-series-x-diablo-iv-bundle",
    image:
      "https://www.jocurinoi.ro/image/cache/wp/cj/data/imported/consola-xbox-series-x-diablo-iv-bundle---xsx-xbox-series-39596/main-340x461.webp",
    sell_price: 778.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Xbox Series X will be the fastest and most powerful console ever and set a new standard for performance, speed and compatibility, allowing you to carry your gaming legacy with you, thousands of games from three generations and more. Its industrial design allows us to deliver four times more processing power than Xbox One X in the quietest and most efficient way, something that is extremely important to deliver truly immersive gameplay. The design supports both portrait and landscape orientation. The new Xbox Wireless Controller will be compatible with Xbox One and Windows 10 PCs.",
  },
  {
    ids: 68,
    name: "Microsoft Xbox 360 console 500 GB",
    slug: "microsoft-xbox-360-console-500gb",
    image:
      "https://images.okr.ro/serve/product/103b590f0f8d6d6120c200ea938750bd-20056-1000_1000",
    sell_price: 129.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "With a new improved design, an internal memory of 500 GB and built-in Wi-Fi, the new Xbox 360 offers you the complete gaming and entertainment experience. In addition, it is compatible with the upcoming Microsoft Kinect control technology. The striking new design and glossy black case mean that the new Xbox 360 looks as good as it performs. Start game!",
  },
  {
    ids: 69,
    name: "Microsoft Xbox 360 E 4GB + Peggle 2 Console",
    slug: "xbox-360-e-4gb-peegle-2",
    image:
      "https://p1.akcdn.net/mid/619368556.microsoft-xbox-360-e-4gb-peggle-2.jpg",
    sell_price: 99.99,
    old_price: 120.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Xbox",
    val: "consoles/xbox",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "These days, everything is wireless. The new Xbox 360 is the only console with integrated Wi-Fi 802.11n. You'll find a limitless connection to ever-expanding entertainment possibilities on Xbox LIVE - including a quick and easy way to watch HD movies and TV and play games with friends around the world. With a new improved design, 4GB HDD and built-in Wi-Fi, the new Xbox 360 offers you the complete gaming and entertainment experience. In addition, it is compatible with Microsoft Kinect.",
  },
  {
    ids: 70,
    name: "Nintendo Wii Console Party Pack",
    slug: "nintendo-wii-console-party-pack",
    image:
      "https://s13emagst.akamaized.net/products/786/785182/images/res_113b817980b2ad7bad345ceea9943479.jpg",
    sell_price: 145.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The Wii is a home video game console developed and brandTypeeted by Nintendo. It was released on November 19, 2006, in North America and in December 2006 for most other regions of the world. It is Nintendo's fifth major home game console, following the GameCube and is a seventh-generation console alongside Microsoft's Xbox 360 and Sony's PlayStation 3.",
  },
  {
    ids: 71,
    name: "Nintendo Wii Console (Includes Sport Pack)",
    slug: "nintendo-wii-console-sport-pack",
    image:
      "https://static3.evomag.ro/img?file=products%2F14%2F14105%2FNIN-WI-SPPACK6.jpg&width=600&height=600&extend=white",
    sell_price: 139.99,
    old_price: 159.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Nintendo Wii console, Comes with the Wii Sports game collection (in total there are 5 games: Tennis, Baseball, Bowling, Golf and Boxing) (Up to 4 players, 480p video output - Widescreen), Console dimensions: Length 21.54cm/ Width 4.4cm/Height 15.7cm, Broadway processor (based on PowerPC architecture, Frequency 729MHz, Construction 90nm), Hollywood graphics chip (produced by ATI, Frequency 243MHz, construction 90nm), RAM 88MB (24MB 1T-SRAM integrated in the graphics package and 64MB GDDR3 SDRAM), 512MB Flash storage (can be increased up to 2GB, through the SD card slot), Up to 4 controllers can be connected to the console (wireless connection via Bluetooth), 2xUSB v.2.0, WiFi Mode 802.11b/g Mitsumi, Compatibility with the GameCube predecessor (Wii can load 8cm GameCube discs as well as its own 12cm ones), Video output of maximum 576i (for GameCube games is 480p), Consumption of 18W when switched on (1.3W when in stand-by)",
  },
  {
    ids: 72,
    name: "Nintendo Switch with Joy-Con Controller",
    slug: "nintendo-switch-with-joy-con-controller",
    image:
      "https://media.gamestop.com/i/gamestop/11095819/Nintendo-Switch-with-Joy-Con-Controller?$pdp2x$",
    sell_price: 259.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Introducing Nintendo Switch, the new home video game system from Nintendo. In addition to providing single and multiplayer thrills at home, the Nintendo Switch system can be taken on the go so players can enjoy a full home Nintendo Switch console experience anytime, anywhere. The mobility of a handheld is now added to the power of a home gaming system, with unprecedented new play styles brought to life by the two new Nintendo Switch Joy-Con controllers.",
  },
  {
    ids: 73,
    name: "Nintendo Switch with Joy-Con Controller (Previous Model)",
    slug: "nintendo-switch-with-joy-con-controller-previous-model",
    image:
      "https://media.gamestop.com/i/gamestop/10141820_neon-blueneon-red?$pdp2x$",
    sell_price: 249.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "At home the system rests in the Nintendo Switch dock, which lets you play with family and friends on a TV in the comfort of your living room. By simply lifting Nintendo Switch from the dock at any time, the system instantly transitions to handheld mode, and the same great gaming experience that was being enjoyed at home now travels with you. The portability of Nintendo Switch is enhanced by its 6.2-inch screen, which displays bright, high-definition gameplay at the park, on an airplane, in a car, or at a friend's apartment. Nintendo Switch comes with two Joy-Con that can each act as a standalone controller with an analog stick, a full complement of face and shoulder buttons, built in motion-sensing technology and new HD Rumble. They can be inserted into a Joy-Con grip accessory to be used like a traditional controller, held comfortably in each hand for independent left and right motion controls, or shared between two players for instant multiplayer gaming in front of the TV or out on the go.",
  },
  {
    ids: 74,
    name: "Nintendo 3DS XL Black",
    slug: "nintendo-3ds-xl-black",
    image:
      "https://media.gamestop.com/i/gamestop/10119890/New-Nintendo-3DS-XL-Black?$pdp2x$",
    sell_price: 149.99,
    old_price: 179.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The Nintendo NEW 3DS XL - Black features face Tracking 3D, The C Stick, Built-in amiibo Support, and more. You can play all Nintendo 3DS, New Nintendo 3DS and most Nintendo DS games in 2D on this system. Colorful and stylish accents, while the sleek clamshell design makes it comfortable to hold; A fast processor offers short loading times",
  },
  {
    ids: 75,
    name: "Nintendo 3DS XL Super Mario Bros. 2 Red",
    slug: "nintendo-3ds-xl-super-mario-bros-2-red",
    image:
      "https://media.gamestop.com/i/gamestop/10129119/Nintendo-3DS-XL-Super-Mario-Bros.-2-Red?$pdp$$&fmt=webp",
    sell_price: 199.99,
    rent_price: 10.0,
    category: "Consoles",
    brand: "Nintendo",
    val: "consoles/nintendo",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Play games and watch videos on the go in full, eye-popping 3D… All without the need for glasses. Experience games from some of the most popular franchises of all time. Nintendo 3DS is backwards compatible with nearly the entire library of Nintendo DS games. Comes built-in with the ability to take photos in 3D, thanks to the two outward-facing lenses.",
  },
  {
    ids: 76,
    name: "Astro Gaming A10 Gen 2 Wired Headset for PlayStation 5, Xbox Series X/S, and PC",
    slug: "astro-gaming-a10-gen-2-wired-headset",
    image:
      "https://media.gamestop.com/i/gamestop/11184368_black/Astro-Gaming-A10-Gen-2-Wired-Headset-for-PlayStation-5-Xbox-Series-X/S-and-PC-black?$pdp2x$",
    sell_price: 59.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Playstation/Xbox/Pc",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Enhance your everyday gaming setup with the ASTRO A10 Headset. Experience explosive audio thanks to 32mm dynamic drivers, flip-to-mute boom mic, and durable construction with replaceable ear cushions and headband pad combine for an unforgettable audio experience.",
  },
  {
    ids: 77,
    name: "Sony PULSE 3D Wireless Gaming Headset for PlayStation 5",
    slug: "sony-pulse-3d-wireless-gaming",
    image: "https://media.gamestop.com/i/gamestop/11106278_whiteblack?$pdp2x$",
    sell_price: 53.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Playstation",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Immerse yourself into your favorite content with the Sony PULSE 3D Wireless Gaming Headset for PlayStation 5. Enjoy a seamless, wireless experience with a headset crafted for 3D on PS5™ consoles. This headset features a new sleek look, noise-cancelling microphones, and easy access controls. Whether you're playing games or live streaming with these wireless PS5 headphones quality audio is delivered.",
  },
  {
    ids: 78,
    name: "Atrix AX-1250 Wireless Gaming Headset for PlayStation/PC",
    slug: "atrix-ax-1250-wireless-gaming-headset",
    image:
      "https://media.gamestop.com/i/gamestop/11173423_black/Atrix-AX-1250-Wireless-Gaming-Headset-for-PS4/PS5/PC-Wired-Compatibility-with-Xbox-One/Xbox-Series-X/Switch-black?$pdp2x$",
    sell_price: 49.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Playstation/PC",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The AX 1250 Wireless Headset from Atrix is a real game-changer. The 5.8Ghz wireless connection ensures you hear everything as it’s happening and never miss a sound. To top that off, you get a 50ft range and a 20hr battery life. Your squad will get its win long before it's time to recharge",
  },
  {
    ids: 79,
    name: "Turtle Beach Recon 70 Wired Gaming Headset for Xbox Series X/S and Xbox One",
    slug: "turtle-beach-recon-70-wired-gaming-headest",
    image: "https://media.gamestop.com/i/gamestop/10174124?$pdp2x$",
    sell_price: 24.99,
    old_price: 30.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Xbox",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Reign victorious with the Recon 70 Wired Gaming Headset for Xbox One. Turtle Beach's latest lightweight and comfortable headset design is made for hours of play. Get the drop on enemies with high-quality 40mm speakers. Feel comfortable after hours of gameplay with a lightweight headband and over-ear premium synthetic leather cushions. This headset allows you to hear every crisp high and thundering low while blocking out unwanted noise.",
  },
  {
    ids: 80,
    name: "SteelSeries Arctis 7P Plus Wireless Gaming Headset for PlayStation 5, PlayStation 4, and PC",
    slug: "steelseries-arctis-7p-plus-wireless-gaming-headset",
    image:
      "https://media.gamestop.com/i/gamestop/11174755/SteelSeries-Arctis-7P-Plus-Wireless-Gaming-Headset-for-PlayStation-5-PlayStation-4-and-PC?$pdp2x$",
    sell_price: 149.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Playstation",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The SteelSeries Arctis 7P+ Wireless headset is designed for powerful next-gen 3D Audio on PlayStation 5, with PlayStation 4 backwards compatibility, and features 30-hour battery life.",
  },
  {
    ids: 81,
    name: "HyperX Cloud Alpha Pro Wired Gaming Headset Universal",
    slug: "hyperx-cloud-alpha-pro-wired-gaming-headset",
    image:
      "https://media.gamestop.com/i/gamestop/10151926/HyperX-Cloud-Alpha-Pro-Wired-Gaming-Headset-Universal?$pdp2x$",
    sell_price: 29.99,
    rent_price: 2.0,
    category: "Accessories",
    brand: "Headset",
    brandType: "Playstation/Xbox/Nintendo/PC",
    val: "accessories/headset",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "HyperX™ Cloud Alpha's groundbreaking Dual Chamber Drivers design gives audio more distinction and clarity by reducing distortion. The dual chambers separate the bass for cleaner, smoother sound. Cloud Alpha has premium red memory foam, an expanded headband and softer, more pliable leatherette, an aluminum frame, detachable braided cable and noise-cancellation microphone.",
  },
  {
    ids: 82,
    name: "Sony DUALSHOCK 4 Black Wireless Controller for PlayStation 4",
    slug: "sony-dualshock-4-black-wireless-controller",
    image:
      "https://media.gamestop.com/i/gamestop/11157867_black/Sony-DUALSHOCK-4-Wireless-Controller-for-PlayStation-4-black?$pdp2x$",
    sell_price: 39.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Playstation",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Experience the power of gaming at your fingertips. The Sony DualShock 4 Wireless Controller for PlayStation 4 enhances your gaming experience. With revolutionary features and comfort with intuitive, precision controls you can fully experience your favorite video games. The analog sticks and trigger buttons deliver greater response and sensitivity along with a multi touch pad for a more natural gameplay.",
  },
  {
    ids: 83,
    name: "PlayStation Move Motion Controller (Styles May Vary)",
    slug: "playstation-move-motion-controller",
    image:
      "https://media.gamestop.com/i/gamestop/10078144/PlayStation-Move-Motion-Controller-Styles-May-Vary?$pdp2x$",
    sell_price: 19.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Playstation",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The sleek PlayStation® Move Motion controller is your key to unlocking an interactive gaming experience. Grab a move motion controller and immerse yourself into all the gaming possibilities. Paired with the PlayStation® Eye camera, the motion controller translates your every move into the game with absolute precision.",
  },
  {
    ids: 84,
    name: "Sony DualSense Wireless Controller for PlayStation 5 - White",
    slug: "sony-dualsense-wireless-controller",
    image:
      "https://media.gamestop.com/i/gamestop/11106262/Sony-DualSense-Wireless-Controller-for-PlayStation-5?$pdp2x$",
    sell_price: 49.99,
    old_price: 59.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Playstation",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Experience the power of gaming at your fingertips. The Sony DualSense Wireless Controller enhances your gaming experience. With revolutionary features and comfort with intuitive, precision controls you can fully experience your favorite video games. This wireless controller offers immersive haptic feedback, dynamic adaptive triggers and a built-in microphone, all integrated into an iconic comfortable design. Take gaming to the next level with this wireless PS5 controller.",
  },
  {
    ids: 85,
    name: "Microsoft Xbox Elite Wireless Controller Series 2 - Core",
    slug: "microsoft-xbox-elite-wireless-controller",
    image:
      "https://media.gamestop.com/i/gamestop/20000552/Microsoft-Xbox-Elite-Wireless-Controller-Series-2---Core?$pdp2x$",
    sell_price: 99.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Xbox",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Experience the Xbox Elite Wireless Controller Series 2 - Core in white, featuring adjustable-tension thumb sticks and shorter hair trigger locks, plus limitless customization with the Xbox Accessories app on Xbox Series X|S, Xbox One, and Windows PC.*",
  },
  {
    ids: 86,
    name: "Microsoft Xbox One Polar White Wireless Controller",
    slug: "microsoft-xbox-360-console-500gb",
    image: "https://media.gamestop.com/i/gamestop/10132012?$pdp2x$",
    sell_price: 46.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Xbox",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Get more out of your gaming experience with the new Xbox Wireless controller with textured grip and Bluetooth technology with twice the wireless range. Elevate your game with a Xbox One controller designed for enhanced comfort during gameplay.",
  },
  {
    ids: 87,
    name: "Microsoft Xbox One Black Wireless Controller",
    slug: "microsoft-xbox-one-black-wireless-controller",
    image: "https://media.gamestop.com/i/gamestop/10136002?$pdp2x$",
    sell_price: 44.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Xbox",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The best controller just got even better. Experience the enhanced comfort and feel of the new Xbox Wireless Controller, featuring a sleek, streamlined design and textured grip. Enjoy custom button mapping and up to twice the wireless range. This Xbox One controller is magic at your fingertips!",
  },
  {
    ids: 88,
    name: "Nintendo Switch Wireless Pro Controller - Black",
    slug: "nintendo-switch-wireless-pro-controller",
    image: "https://media.gamestop.com/i/gamestop/10141852?$pdp2x$",
    sell_price: 68.99,
    old_price: 59.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Nintendo",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Take your gaming to the next level with the Nintendo Switch Pro Controller. This Nintendo Switch Wireless Pro Controller includes motion controls, HD rumble, built-in amiibo functionality, and more. This Switch controller is designed to go wherever you go. It works with any mode, whether or not the console is docked. So you get more time to play the games you love, anyway you like.",
  },
  {
    ids: 89,
    name: "Nintendo Switch Joy-Con Grip",
    slug: "nintendo-switch-joy-con-grip",
    image:
      "https://media.gamestop.com/i/gamestop/10148091/Nintendo-Switch-Joy-Con-Grip?$pdp2x$",
    sell_price: 3.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Nintendo",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Amplify your game with Nintendo's first-party Joy-Con grip. This pre-owned grip comes with GameStop's pre-owned guarantee and Nintendo's level of quality, ensuring complete satisfaction when it's time to slip the left and right Joy-Cons into place. When it comes to playing first-person shooters on the Nintendo Switch, the Joy-Con Grip is a must-have peripheral that simulates a classic controller design. Designers modeled it with ergonomic grips for maximum comfort and reduced fatigue over long periods of play.",
  },
  {
    ids: 90,
    name: "HORI Switch Split Pad Pro Controller for Nintendo Switch Black",
    slug: "hori-switch-split-pad-pro-controller",
    image:
      "https://media.gamestop.com/i/gamestop/11177015/Hori-Switch-Split-Pad-Pro-Controller-for-Nintendo-Switch-Black?$pdp2x$",
    sell_price: 19.99,
    old_price: 29.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "Nintendo",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "A revolutionary way to play your Nintendo Switch! Enjoy the full-size Nintendo Switch controller experience in handheld mode with the HORI Split Pad Pro. Featuring full-size analog sticks, precision D-pad, and large shoulder buttons designed for comfort and accuracy, even for marathon gaming sessions. Advanced features include programmable rear triggers, Turbo functionally, assignable buttons, and more. Perfect for high-pace action titles such as Daemon X Machina and many other Nintendo Switch titles. Enhance your gaming experience with the Split Pad Pro! Officially Licensed by Nintendo. (Not a wireless controller - only for handheld mode. Does not include HD Rumble, NFC, or IR camera.)",
  },
  {
    ids: 91,
    name: "Atrix Ergonomic Wireless Controller for PC",
    slug: "atrix-ergonomic-wireless-controller",
    image:
      "https://media.gamestop.com/i/gamestop/11155947/Atrix-Ergonomic-Wireless-Controller-for-Nintendo-Switch-PC-Android-and-Steamdeck?$pdp$$&fmt=webp",
    sell_price: 26.58,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "PC",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Seamlessly switch between your favorite PC, Android, and Switch games and devastate the competition with our ergonomic Bluetooth gaming controller. This Bluetooth mobile controller blends performance and comfort with soft-touch coating and enhanced grip sections. Compatible with Android, PC, and Nintendo Switch titles, this gaming controller is perfect for multi-platform gamers that value build quality and versatility.",
  },
  {
    ids: 92,
    name: "Logitech Driving Force Shifter",
    slug: "logitech-driving-force-shifter",
    image:
      "https://media.gamestop.com/i/gamestop/10166665/Logitech-G-Driving-Force-Shifter-for-G923-G29-and-G920-Racing-Wheels?$pdp2x$",
    sell_price: 59.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "PC",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Relentlessly engineered for the perfect driving experience, Driving Force by Logitech G takes the latest racing games to the highest level. You simply haven't experienced racing simulation if you haven't grabbed your supercar by the wheel. Driving Force Shifter is designed for both G29 and G920 Driving Force racing wheels, to enhance the latest PC and console racing titles. Add Driving Force Shifter to your racing wheel setup to complete your racing rig for a more realistic experience.",
  },
  {
    ids: 93,
    name: "G920 Driving Force Racing Wheel for PC",
    slug: "g920-driving-force-racing-wheel",
    image:
      "https://media.gamestop.com/i/gamestop/10126519/Logitech-G920-Driving-Force-Racing-Wheel-for-Xbox-One-and-PC?$pdp2x$",
    sell_price: 199.99,
    rent_price: 3.0,
    category: "Accessories",
    brand: "Controller",
    brandType: "PC",
    val: "accessories/controller",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Logitech G920 Driving Force Steering Wheel is the definitive sim racing wheel for the latest Xbox One™ and PC titles. With realistic dual-motor force feedback and helical gearing for quiet, smooth steering. On-wheel controls and paddle shifters are easy to access so you can make crisp, precise gear transitions. The separate pedal unit gives you natural, responsive control, with a nonlinear brake pedal that mimics the feel of high-performance vehicles. Driving Force racing wheel for Xbox One is built for comfort and durability with hand-stitched leather and stainless steel components. Built-in clamps and bolt points keeps Logitech Driving Force racing wheel mounted securely to a table or racing rig, minimizing shifting or wobbling during aggressive maneuvers.",
  },
  {
    ids: 94,
    name: "PlayStation Store Gift Card $25",
    slug: "playstation-store-gift-card-$25",
    image: "https://media.gamestop.com/i/gamestop/10084722-10167528?$pdp2x$",
    sell_price: 25.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Playstation",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Get the PlayStation Gift Card and discover thousands of PlayStation games. It's the Ultimate Entertainment Gift Card for gamers. PlayStation®Store Gift Cards fill your PSN Wallet with cash, allowing you to download new games, DLC, and videos, as well as stream movies and music. The all-new PlayStation®Store experience is here! The PlayStation®Network card is an easy and convenient way to make your PlayStation®Store purchase without using a credit card. PSN cards are available for purchase at a variety of retail stores throughout the United States and Canada.",
  },
  {
    ids: 95,
    name: "PlayStation Store Gift Card $50",
    slug: "playstation-store-gift-card-$50",
    image: "https://media.gamestop.com/i/gamestop/10084722-10084723?$pdp2x$",
    sell_price: 50.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Playstation",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Get the PlayStation Gift Card and discover thousands of PlayStation games. It's the Ultimate Entertainment Gift Card for gamers. PlayStation®Store Gift Cards fill your PSN Wallet with cash, allowing you to download new games, DLC, and videos, as well as stream movies and music. The all-new PlayStation®Store experience is here! The PlayStation®Network card is an easy and convenient way to make your PlayStation®Store purchase without using a credit card. PSN cards are available for purchase at a variety of retail stores throughout the United States and Canada.",
  },
  {
    ids: 96,
    name: "PlayStation Store Gift Card $100",
    slug: "playstation-store-gift-card-$100",
    image: "https://media.gamestop.com/i/gamestop/10084722-10115472?$pdp2x$",
    sell_price: 100.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Playstation",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Get the PlayStation Gift Card and discover thousands of PlayStation games. It's the Ultimate Entertainment Gift Card for gamers. PlayStation®Store Gift Cards fill your PSN Wallet with cash, allowing you to download new games, DLC, and videos, as well as stream movies and music. The all-new PlayStation®Store experience is here! The PlayStation®Network card is an easy and convenient way to make your PlayStation®Store purchase without using a credit card. PSN cards are available for purchase at a variety of retail stores throughout the United States and Canada.",
  },
  {
    ids: 97,
    name: "Xbox Gift Card $10",
    slug: "xbox-gift-card-$10",
    image:
      "https://media.gamestop.com/i/gamestop/10111819/Xbox-Gift-Card-$10?$pdp2x$",
    sell_price: 10.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Xbox",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "Buy an Xbox Gift Card for yourself or a friend to get great games and entertainment on Xbox consoles and Windows PCs. Choose from hundreds of games, from AAA to indie, and play the day they're released with a Game Pass membership. Extend the experience in your favorite games with add-ons and in-game currency. Browse a massive library of new and popular movies and TV shows to rent or buy. Xbox Gift Cards are easy to use, never expire, and give the freedom to pick the gift they want. Enjoy more ways to play without a credit card attached to your Microsoft account.",
  },
  {
    ids: 98,
    name: "Xbox Gift Card $20",
    slug: "xbox-gift-card-$20",
    image:
      "https://media.gamestop.com/i/gamestop/10111820/Xbox-Gift-Card-$20?$pdp2x$",
    sell_price: 20.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Xbox",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Buy an Xbox Gift Card for yourself or a friend to get great games and entertainment on Xbox consoles and Windows PCs. Choose from hundreds of games, from AAA to indie, and play the day they're released with a Game Pass membership. Extend the experience in your favorite games with add-ons and in-game currency. Browse a massive library of new and popular movies and TV shows to rent or buy. Xbox Gift Cards are easy to use, never expire, and give the freedom to pick the gift they want. Enjoy more ways to play without a credit card attached to your Microsoft account.",
  },
  {
    ids: 99,
    name: "Xbox Gift Card $50",
    slug: "xbox-gift-card-$50",
    image:
      "https://media.gamestop.com/i/gamestop/10111821/Xbox-Gift-Card-$50?$pdp2x$",
    sell_price: 50.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Xbox",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Buy an Xbox Gift Card for yourself or a friend to get great games and entertainment on Xbox consoles and Windows PCs. Choose from hundreds of games, from AAA to indie, and play the day they're released with a Game Pass membership. Extend the experience in your favorite games with add-ons and in-game currency. Browse a massive library of new and popular movies and TV shows to rent or buy. Xbox Gift Cards are easy to use, never expire, and give the freedom to pick the gift they want. Enjoy more ways to play without a credit card attached to your Microsoft account.",
  },
  {
    ids: 100,
    name: "Nintendo eShop $10",
    slug: "nintendo-eshop-$10",
    image: "https://media.gamestop.com/i/gamestop/10138750?$pdp2x$",
    sell_price: 10.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Nintendo",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The perfect gift for anyone who loves to play—including you. Choose from over 1,000 new, classic and indie games - delivered directly to your Nintendo Switch. Give the gift of fun with a Nintendo eShop gift code. Choose the price that's right for you",
  },
  {
    ids: 101,
    name: "Nintendo eShop $20",
    slug: "nintendo-eshop-$20",
    image: "https://media.gamestop.com/i/gamestop/10129933?$pdp2x$",
    sell_price: 20.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Nintendo",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    related: true,
    description:
      "The perfect gift for anyone who loves to play—including you. Choose from over 1,000 new, classic and indie games - delivered directly to your Nintendo Switch. Give the gift of fun with a Nintendo eShop gift code. Choose the price that's right for you",
  },
  {
    ids: 102,
    name: "Nintendo eShop $50",
    slug: "nintendo-eshop-$50",
    image: "https://media.gamestop.com/i/gamestop/10129932?$pdp2x$",
    sell_price: 50.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "Nintendo",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "The perfect gift for anyone who loves to play—including you. Choose from over 1,000 new, classic and indie games - delivered directly to your Nintendo Switch. Give the gift of fun with a Nintendo eShop gift code. Choose the price that's right for you",
  },
  {
    ids: 103,
    name: "Valve Steam Wallet Card $20",
    slug: "valve-steam-wallet-card-$20",
    image: "https://media.gamestop.com/i/gamestop/10116382?$pdp2x$",
    sell_price: 20.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "PC",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Download and play thousands of your favorite games with the Steam Wallet Card. Steam Gift Cards and Wallet Codes are an easy way to put money into your own Steam Wallet or give the perfect gift of games to your friend or family member.",
  },
  {
    ids: 104,
    name: "Valve Steam Wallet Card $50",
    slug: "valve-steam-wallet-card-$50",
    image: "https://media.gamestop.com/i/gamestop/10116383?$pdp2x$",
    sell_price: 50.0,
    category: "Accessories",
    brand: "Gift Cards",
    brandType: "PC",
    val: "accessories/cards",
    sellInStock: 20,
    rentInStock: 20,
    description:
      "Download and play thousands of your favorite games with the Steam Wallet Card. Steam Gift Cards and Wallet Codes are an easy way to put money into your own Steam Wallet or give the perfect gift of games to your friend or family member.",
  },
];

export const types = [
  {
    ids: 1,
    category: "Games",
    img: "https://blog.playstation.com/tachyon/2023/03/0c2eda8bd87db0918edbf5216ee81cac4d670623.jpeg",
    goto: "/games/playstation",
  },
  {
    ids: 2,
    category: "Games",
    img: "https://i0.wp.com/news.xbox.com/en-us/wp-content/uploads/sites/2/xboxlogoHERO-1-hero-1-hero.jpg?resize=940%2C528&ssl=1",
    goto: "/games/xbox",
  },
  {
    ids: 3,
    category: "Games",
    img: "https://cdn.dribbble.com/users/1869705/screenshots/11189050/intro_4x.png",
    goto: "/games/nintendo",
  },
  {
    ids: 4,
    category: "Games",
    img: "/images/pc.jpg",
    goto: "/games/pC",
  },
  {
    ids: 5,
    category: "Consoles",
    img: "https://www.stuff.tv/wp-content/uploads/sites/2/2023/02/Sony-PlayStation-Consoles-Ranked-2023.jpg?w=1080",
    goto: "/consoles/playstation",
  },
  {
    ids: 6,
    category: "Consoles",
    img: "https://www.stuff.tv/wp-content/uploads/sites/2/2023/02/Best-Xbox-consoles-ever-lead.jpg?w=1080",
    goto: "/consoles/xbox",
  },
  {
    ids: 7,
    category: "Consoles",
    img: "https://retrododo.com/wp-content/uploads/2022/08/all_nintendo.jpg",
    goto: "/consoles/nintendo",
  },
  {
    ids: 8,
    category: "Accessories",
    img: "/images/accessories.jpg",
    goto: "/accessories/headset",
  },
  {
    ids: 9,
    category: "Accessories",
    img: "/images/controller.jpg",
    goto: "/accessories/controller",
  },
  {
    ids: 10,
    category: "Accessories",
    img: "/images/cards.jpg",
    goto: "/accessories/cards",
  },
  {
    ids: 11,
    category: "Categories",
    img: "https://www.pcworld.com/wp-content/uploads/2023/04/playstation-studios.jpg?quality=50&strip=all&w=1024",
    title: "VIDEO GAMES",
    goto: "/games",
  },
  {
    ids: 12,
    category: "Categories",
    img: "/images/consoles.jpg",
    title: "CONSOLES",
    goto: "/consoles",
  },
  {
    ids: 13,
    category: "Categories",
    img: "https://www.cnet.com/a/img/resize/e1f8da5e4cac42f3b95038b9a7d05b8a648af8a4/hub/2019/09/19/c08ea3ba-d393-4e19-a230-9e9a8f0017c9/100-nintendo-switch-accessories-listicle-2019.jpg?auto=webp&fit=crop&height=675&width=1200",
    title: "ACCESSORIES",
    goto: "/accessories",
  },
];
